version: 2.1
orbs:
  docker: circleci/docker@2.6.0
jobs:
  build-and-push-image-api-feed:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - run: 'docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD'
      - run: docker build -t backend-feed ./udagram-api-feed
      - run: docker tag backend-feed thangplcdocker/udagram-api-feed
      - run: docker push thangplcdocker/udagram-api-feed
  build-and-push-image-api-user:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - run: 'docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD'
      - run: docker build -t backend-user ./udagram-api-user
      - run: docker tag backend-user thangplcdocker/udagram-api-user
      - run: docker push thangplcdocker/udagram-api-user
  build-and-push-image-api-frontend:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - run: 'docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD'
      - run: docker build -t frontend ./udagram-frontend
      - run: docker tag frontend thangplcdocker/udagram-frontend
      - run: docker push thangplcdocker/udagram-frontend
  build-and-push-image-api-reverseproxy:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - run: 'docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD'
      - run: docker build -t reverseproxy ./reverseproxy
      - run: docker tag reverseproxy thangplcdocker/reverseproxy
      - run: docker push thangplcdocker/reverseproxy
workflows:
  commit:
    jobs:
      - build-and-push-image-api-feed
      - build-and-push-image-api-user
      - build-and-push-image-api-frontend
      - build-and-push-image-api-reverseproxy


