version: 2.1
executors:
  thangplc-executor-docker:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/thangplc/project_3_udacity_cloud_develop/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  build_push_udagram_api_feed:
    executor: thangplc-executor-docker
    steps:
      - setup_remote_docker
      - checkout
      - run: echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run: docker build -t backend-feed ./udagram-api-feed
      - run: docker tag backend-feed thangplcdocker/udagram-api-feed
      - run: docker push thangplcdocker/udagram-api-feed
  build_push_udagram_api_user:
    executor: thangplc-executor-docker
    steps:
      - setup_remote_docker
      - checkout
      - run: echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run: docker build -t backend-user ./udagram-api-user
      - run: docker tag backend-user thangplcdocker/udagram-api-user
      - run: docker push thangplcdocker/udagram-api-user
  build_push_udagram_frontend:
    executor: thangplc-executor-docker
    steps:
      - setup_remote_docker
      - checkout
      - run: echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run: docker build -t frontend ./udagram-frontend
      - run: docker tag frontend thangplcdocker/udagram-frontend
      - run: docker push thangplcdocker/udagram-frontend
  build_push_reverseproxy:
    executor: thangplc-executor-docker
    steps:
      - setup_remote_docker
      - checkout
      - run: echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run: docker build -t reverseproxy ./udagram-reverseproxy
      - run: docker tag reverseproxy thangplcdocker/reverseproxy
      - run: docker push thangplcdocker/reverseproxy

workflows:
  thangplc-workflow:
    jobs:
      - build_push_udagram_api_feed
      - build_push_udagram_api_user
      - build_push_udagram_frontend
      - build_push_reverseproxy