version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:16  # Sử dụng Node.js, bạn có thể thay đổi theo nhu cầu
    steps:
      - checkout  # Clone code từ repo
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test

  deploy:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Build project
          command: npm run build
      - run:
          name: Deploy to production
          command: ./deploy.sh  # Tùy chỉnh script deploy của bạn

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build  # Chạy deploy chỉ khi build thành công
