# apiVersion: v1
# kind: Service
# metadata:
#   name: backend-user
#   labels:
#     run: backend-user
# spec:
#   ports:
#     - port: 8080
#       protocol: TCP
#       name: http
#   selector:
#     app: backend-user


apiVersion: v1
kind: Service
metadata:
  name: backend-user
  labels:
    run: backend-user
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    run: backend-user