apiVersion: v1
kind: Service
metadata:
  name: backend-api-user
  labels:
    run: backend-api-user
spec:
  ports:
    - port: 8080
      protocol: TCP
      name: http
  selector:
    app: backend-api-user