# apiVersion: v1
# kind: Service
# metadata:
#   name: reverseproxy
#   labels:
#     run: reverseproxy
# spec:
#   ports:
#     - port: 80
#       protocol: TCP
#   selector:
#     app: reverseproxy


apiVersion: v1
kind: Service
metadata:
  name: reverseproxy
  labels:
    run: reverseproxy
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: reverseproxy
#  type: LoadBalancer    